wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  entity: jet-diffusion
  offline: False
  id: null
  log_model: False
  project: ${project_name}
  name: ${network_name}
  save_dir: ${paths.full_path}
  resume: ${full_resume}
